package com.smartqueue.service;

import com.smartqueue.dto.TokenRequest;
import com.smartqueue.dto.CategoryQueueStatus;
import com.smartqueue.dto.CounterQueueStatus;
import com.smartqueue.entity.Category;
import com.smartqueue.entity.Counter;
import com.smartqueue.entity.CounterStatus;
import com.smartqueue.entity.PriorityType;
import com.smartqueue.entity.QueueLog;
import com.smartqueue.entity.Token;
import com.smartqueue.entity.TokenStatus;
import com.smartqueue.entity.User;
import com.smartqueue.repository.CategoryRepository;
import com.smartqueue.repository.CounterRepository;
import com.smartqueue.repository.QueueLogRepository;
import com.smartqueue.repository.TokenRepository;
import com.smartqueue.repository.UserRepository;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Comparator;
import java.util.List;
import java.util.Optional;
import java.util.Set;
import java.util.function.Predicate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class TokenService {

    private static final List<TokenStatus> ACTIVE_STATUSES = List.of(
            TokenStatus.WAITING,
            TokenStatus.CALLED,
            TokenStatus.SKIPPED
    );

    private final TokenRepository tokenRepository;
    private final UserRepository userRepository;
    private final CategoryRepository categoryRepository;
    private final CounterRepository counterRepository;
    private final QueueLogRepository queueLogRepository;

    public TokenService(TokenRepository tokenRepository,
                        UserRepository userRepository,
                        CategoryRepository categoryRepository,
                        CounterRepository counterRepository,
                        QueueLogRepository queueLogRepository) {
        this.tokenRepository = tokenRepository;
        this.userRepository = userRepository;
        this.categoryRepository = categoryRepository;
        this.counterRepository = counterRepository;
        this.queueLogRepository = queueLogRepository;
    }

    @Transactional
    public Token generateToken(String userEmail, TokenRequest request) {
        User user = userRepository.findByEmail(userEmail)
                .orElseThrow(() -> new IllegalArgumentException("User not found"));
        Category category = categoryRepository.findById(request.getCategoryId())
                .orElseThrow(() -> new IllegalArgumentException("Category not found"));
        Counter counter = counterRepository.findById(request.getCounterId())
                .orElseThrow(() -> new IllegalArgumentException("Counter not found"));

        if (!category.isActive()) {
            throw new IllegalArgumentException("Selected category is not active");
        }

        if (!counter.isActive() || counter.getStatus() != CounterStatus.OPEN || !counter.getCategory().getId().equals(category.getId())) {
            throw new IllegalArgumentException("Selected counter is not available for this category");
        }

        if (tokenRepository.existsByUserEmailAndCategoryIdAndStatusIn(userEmail, category.getId(), ACTIVE_STATUSES)) {
            throw new IllegalArgumentException("You already have an active token in this category");
        }

        Token token = new Token();
        token.setTokenNumber(generateTokenNumber(category));
        token.setUser(user);
        token.setCategory(category);
        token.setCounter(counter);
        token.setPriorityType(request.getPriorityType());
        token.setStatus(TokenStatus.WAITING);
        Token savedToken = tokenRepository.save(token);
        recalculateEstimatesForCategory(category.getId());
        log(savedToken, "GENERATED", "Token generated by user");
        return savedToken;
    }

    @Transactional(readOnly = true)
    public List<Token> recentTokens() {
        return tokenRepository.findTop10ByOrderByIssuedAtDesc();
    }

    @Transactional(readOnly = true)
    public List<Token> allTokens() {
        return tokenRepository.findAllByOrderByIssuedAtDesc();
    }

    @Transactional(readOnly = true)
    public List<Token> tokensForUser(String email) {
        return tokenRepository.findByUserEmailOrderByIssuedAtDesc(email);
    }

    @Transactional(readOnly = true)
    public Optional<Token> currentActiveToken(String email) {
        return tokenRepository.findFirstByUserEmailAndStatusInOrderByIssuedAtDesc(email, ACTIVE_STATUSES);
    }

    @Transactional(readOnly = true)
    public List<Counter> availableCountersForCategory(Long categoryId) {
        if (categoryId == null) {
            return List.of();
        }
        return counterRepository.findByCategoryIdAndActiveTrueAndStatus(categoryId, CounterStatus.OPEN);
    }

    @Transactional(readOnly = true)
    public List<Token> waitingTokens() {
        return tokenRepository.findByStatusOrderByIssuedAtAsc(TokenStatus.WAITING).stream()
                .sorted(smartQueueComparator())
                .toList();
    }

    @Transactional(readOnly = true)
    public List<Token> waitingTokensForStaff(String staffEmail) {
        Set<Long> assignedCounterIds = assignedCounters(staffEmail).stream()
                .map(Counter::getId)
                .collect(java.util.stream.Collectors.toSet());

        if (assignedCounterIds.isEmpty()) {
            return List.of();
        }

        return waitingTokens().stream()
                .filter(token -> token.getCounter() != null && assignedCounterIds.contains(token.getCounter().getId()))
                .toList();
    }

    @Transactional(readOnly = true)
    public List<Counter> assignedCounters(String staffEmail) {
        return counterRepository.findByAssignedStaffEmailAndActiveTrue(staffEmail);
    }

    @Transactional(readOnly = true)
    public List<CounterQueueStatus> counterQueueStatuses(String staffEmail) {
        return assignedCounters(staffEmail).stream()
                .map(counter -> new CounterQueueStatus(
                        counter,
                        tokenRepository.findFirstByCounterIdAndStatusOrderByCalledAtDesc(counter.getId(), TokenStatus.CALLED),
                        nextSmartTokenForCounter(counter),
                        tokenRepository.countByCounterIdAndStatus(counter.getId(), TokenStatus.WAITING)
                ))
                .filter(status -> status.waitingCount() > 0 || status.calledToken().isPresent())
                .toList();
    }

    @Transactional(readOnly = true)
    public List<CategoryQueueStatus> categoryQueueStatuses() {
        return categoryRepository.findByActiveTrueOrderByNameAsc().stream()
                .map(category -> new CategoryQueueStatus(
                        category,
                        tokenRepository.countByCategoryIdAndStatus(category.getId(), TokenStatus.WAITING),
                        tokenRepository.countByCategoryIdAndStatus(category.getId(), TokenStatus.CALLED),
                        tokenRepository.countByCategoryIdAndStatus(category.getId(), TokenStatus.COMPLETED)
                ))
                .filter(status -> status.waitingCount() > 0)
                .toList();
    }

    @Transactional
    public Token callNextToken(Long counterId, String staffEmail) {
        Counter counter = counterRepository.findById(counterId)
                .orElseThrow(() -> new IllegalArgumentException("Counter not found"));
        ensureCounterAssignedToStaff(counter, staffEmail);
        ensureCounterCanServe(counter);
        ensureNoTokenCurrentlyCalled(counter);

        Token token = nextSmartTokenForCounter(counter)
                .orElseThrow(() -> new IllegalStateException("No waiting tokens for this counter"));
        token.setCounter(counter);
        token.setStatus(TokenStatus.CALLED);
        token.setCalledAt(LocalDateTime.now());
        token.setEstimatedWaitMinutes(0);
        recalculateEstimatesForCategory(counter.getCategory().getId());
        log(token, "CALLED", "Token called at " + counter.getCode());
        return token;
    }

    @Transactional
    public Token recallCurrentToken(Long counterId, String staffEmail) {
        Counter counter = counterRepository.findById(counterId)
                .orElseThrow(() -> new IllegalArgumentException("Counter not found"));
        ensureCounterAssignedToStaff(counter, staffEmail);
        Token token = tokenRepository.findFirstByCounterIdAndStatusOrderByCalledAtDesc(counterId, TokenStatus.CALLED)
                .orElseThrow(() -> new IllegalStateException("No called token to recall"));
        token.setCalledAt(LocalDateTime.now());
        log(token, "RECALLED", "Token recalled at " + counter.getCode());
        return token;
    }

    @Transactional
    public void skipToken(Long tokenId, String staffEmail) {
        Token token = getToken(tokenId);
        requireStatus(token, TokenStatus.CALLED, "Only a called token can be skipped");
        ensureTokenBelongsToStaffCounter(token, staffEmail);
        token.setStatus(TokenStatus.SKIPPED);
        token.setCalledAt(null);
        token.setCounter(null);
        token.setEstimatedWaitMinutes(0);
        recalculateEstimatesForCategory(token.getCategory().getId());
        log(token, "SKIPPED", "Token skipped by staff");
    }

    @Transactional
    public void completeToken(Long tokenId, String staffEmail) {
        Token token = getToken(tokenId);
        requireStatus(token, TokenStatus.CALLED, "Only a called token can be completed");
        ensureTokenBelongsToStaffCounter(token, staffEmail);
        token.setStatus(TokenStatus.COMPLETED);
        token.setCompletedAt(LocalDateTime.now());
        token.setEstimatedWaitMinutes(0);
        recalculateEstimatesForCategory(token.getCategory().getId());
        log(token, "COMPLETED", "Token completed by staff");
    }

    @Transactional
    public void recalculateEstimatesForCategory(Long categoryId) {
        List<Token> waitingTokens = tokenRepository.findByCategoryIdAndStatus(categoryId, TokenStatus.WAITING).stream()
                .sorted(smartQueueComparator())
                .toList();

        for (Token token : waitingTokens) {
            token.setEstimatedWaitMinutes(calculateEstimatedWaitForToken(token, waitingTokens));
        }
    }

    @Transactional
    public void recalculateEstimatesForCounter(Long counterId) {
        Counter counter = counterRepository.findById(counterId)
                .orElseThrow(() -> new IllegalArgumentException("Counter not found"));
        recalculateEstimatesForCategory(counter.getCategory().getId());
    }

    private Token getToken(Long tokenId) {
        return tokenRepository.findById(tokenId)
                .orElseThrow(() -> new IllegalArgumentException("Token not found"));
    }

    private Optional<Token> nextSmartTokenForCounter(Counter counter) {
        Predicate<Token> canServeAtCounter = token ->
                token.getCounter() == null || token.getCounter().getId().equals(counter.getId());

        return tokenRepository.findByCategoryIdAndStatus(counter.getCategory().getId(), TokenStatus.WAITING).stream()
                .sorted(smartQueueComparator())
                .filter(canServeAtCounter)
                .findFirst();
    }

    private Comparator<Token> smartQueueComparator() {
        // Smart queue rule: serve higher priority first; if priority is same, serve the older token first.
        return Comparator.comparingInt((Token token) -> priorityRank(token.getPriorityType()))
                .thenComparing(Token::getIssuedAt);
    }

    private int priorityRank(PriorityType priorityType) {
        return switch (priorityType) {
            case EMERGENCY -> 1;
            case SENIOR_CITIZEN -> 2;
            case VIP -> 3;
            case NORMAL -> 4;
        };
    }

    private void ensureCounterCanServe(Counter counter) {
        if (!counter.isActive() || counter.getStatus() != CounterStatus.OPEN) {
            throw new IllegalStateException("Counter is not open");
        }
    }

    private void ensureNoTokenCurrentlyCalled(Counter counter) {
        if (tokenRepository.findFirstByCounterIdAndStatusOrderByCalledAtDesc(counter.getId(), TokenStatus.CALLED).isPresent()) {
            throw new IllegalStateException("Complete, skip, or recall the current token before calling another");
        }
    }

    private void ensureCounterAssignedToStaff(Counter counter, String staffEmail) {
        if (counter.getAssignedStaff() == null || !counter.getAssignedStaff().getEmail().equals(staffEmail)) {
            throw new IllegalStateException("This counter is not assigned to your staff account");
        }
    }

    private void ensureTokenBelongsToStaffCounter(Token token, String staffEmail) {
        if (token.getCounter() == null) {
            throw new IllegalStateException("Token is not assigned to a counter");
        }
        ensureCounterAssignedToStaff(token.getCounter(), staffEmail);
    }

    private void requireStatus(Token token, TokenStatus requiredStatus, String message) {
        if (token.getStatus() != requiredStatus) {
            throw new IllegalStateException(message);
        }
    }

    private int calculateEstimatedWaitForToken(Token targetToken, List<Token> orderedWaitingTokens) {
        Counter counter = targetToken.getCounter();
        int averageMinutes = counter == null ? 10 : counter.getAverageServiceTimeInMinutes();

        /*
         * Practical college-project formula:
         * 1. Sort waiting tokens by smart queue order: priority first, then issued time.
         * 2. Count only tokens ahead of this token that can be served by the same counter.
         * 3. estimated wait = tokens ahead * selected counter average service time.
         */
        long tokensAhead = orderedWaitingTokens.stream()
                .takeWhile(token -> !token.getId().equals(targetToken.getId()))
                .filter(token -> sameServiceLine(token, targetToken))
                .count();
        return (int) tokensAhead * averageMinutes;
    }

    private boolean sameServiceLine(Token token, Token targetToken) {
        if (targetToken.getCounter() == null) {
            return token.getCategory().getId().equals(targetToken.getCategory().getId());
        }
        return token.getCounter() == null || token.getCounter().getId().equals(targetToken.getCounter().getId());
    }

    private String generateTokenNumber(Category category) {
        LocalDate today = LocalDate.now();
        long todaysTokenCount = tokenRepository.countByCategoryIdAndIssuedAtBetween(
                category.getId(),
                today.atStartOfDay(),
                today.plusDays(1).atStartOfDay()
        );
        return categoryPrefix(category) + "-" + String.format("%03d", todaysTokenCount + 1);
    }

    private String categoryPrefix(Category category) {
        String storedPrefix = category.getTokenPrefix();
        if (storedPrefix != null && !storedPrefix.isBlank()) {
            return storedPrefix.trim().replaceAll("[^A-Za-z0-9]", "").toUpperCase();
        }
        return fallbackPrefix(category);
    }

    private String fallbackPrefix(Category category) {
        String letters = category.getName().replaceAll("[^A-Za-z]", "").toUpperCase();
        return letters.length() < 3 ? "SQM" : letters.substring(0, 3);
    }

    private void log(Token token, String action, String remarks) {
        QueueLog queueLog = new QueueLog();
        queueLog.setToken(token);
        queueLog.setAction(action);
        queueLog.setRemarks(remarks);
        queueLogRepository.save(queueLog);
    }
}
